---
mortality:
  expt_death: par + spore
  survival_shape: 1
  ratio_expt_death: not_fitted
  prob_death: not_fitted
  sex_ratio: not_fitted
reproduction:
  expt_reproduction: not_fitted
  reproduction_shape: not_fitted
  n_offspring: not_fitted
  increase_death_hazard: not_fitted
  tof_reduction_date: not_fitted
  increase_tof_n_offspring: not_fitted
  lin_decrease_hazard: not_fitted
  quad_decrease_hazard: not_fitted
  lin_change_n_offspring: not_fitted
  quad_change_n_offspring: not_fitted
  tof_n_offspring: not_fitted
maturity:
  expt_maturity: not_fitted
  maturity_shape: not_fitted
  ratio_expt_maturity: not_fitted
